language : generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mayerjeon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mayerjeon/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-516011348887"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"